services:
  # server:
  #   build:
  #     context: .
  #   container_name: dermit_backend_server
  #   ports:
  #     - 8000:8000
  #   depends_on:
      # - redis

  redis:
    image: redis
    container_name: dermit_local_redis
    ports:
      - 6379:6379



