from typing import List
from langchain_core.pydantic_v1 import BaseModel, Field

class Response(BaseModel):
    # def __init__(*args, **kwargs):
    #     super().__init__(*args, **kwargs)
        
    """Structured details of the detected disease to be generated by the LLM"""
    
    Name: str = Field(description="Name of the identified disease")
    Symptoms: list = Field(description="Explain each symptom in point-wise manner")
    Cause: list = Field(description="Elaborate the causes of the disease")
    Lifestyle_changes: list = Field(
        description="Describes the possible life stye changes that can be subscribed to prevent the disease"
    )
    Background_of_the_disease: str = Field(
        description="Describe the background of the diagnosed disease."
    )