# Generated by Django 4.2.11 on 2024-04-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
