# Generated by Django 4.2.11 on 2024-05-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='response',
        ),
        migrations.AddField(
            model_name='message',
            name='is_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(max_length=512),
        ),
    ]
