# Generated by Django 4.2.11 on 2024-05-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="image",
            field=models.ImageField(
                default="",
                upload_to="D:\\Machine Learning Projects\\DermIT\\web-app\\dermit-backend/chat/Images",
            ),
        ),
    ]
