# Generated by Django 4.2.11 on 2024-05-31 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_image_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="name",
            field=models.CharField(max_length=256),
        ),
    ]
