# Generated by Django 4.2.11 on 2024-06-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_alter_image_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                default="",
                upload_to="D:\\Machine Learning Projects\\DermIT\\web-app\\dermit-backend/chat/Images/Input",
            ),
        ),
    ]
